-- NameHim Supabase schema and policies (updated: no description column)

create table if not exists public.reports (
  id serial primary key,
  name text not null,
  city text not null,
  state varchar(10),
  country text not null,
  categories text[] not null,
  created_at timestamptz not null default now(),
  submitter_uuid text not null
);

alter table public.reports enable row level security;

-- Public read access
create policy if not exists "Public can read reports"
on public.reports
for select
using (true);

-- Public insert access (client-side Turnstile + rate limiting; server-side verification recommended for production)
create policy if not exists "Public can insert reports"
on public.reports
for insert
to anon, authenticated
with check (true);

-- Optional table for future moderation reports
create table if not exists public.report_flags (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.reports(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.report_flags enable row level security;

create policy if not exists "Public can insert report flags"
on public.report_flags
for insert
to anon, authenticated
with check (true);

create policy if not exists "Public can read report flags"
on public.report_flags
for select
using (true);
